2022-05-13 18:06:46,006 - zhuochuang_sj.py[line:762] - WARNING: (2003, "Can't connect to MySQL server on '27.150.182.135' (timed out)")
2022-05-13 18:43:40,670 - zhuochuang_sj.py[line:758] - WARNING: (2003, "Can't connect to MySQL server on '27.150.182.135' (timed out)")
2022-05-13 19:54:24,070 - zhuochuang_sj.py[line:758] - WARNING: (2003, "Can't connect to MySQL server on '27.150.182.135' (timed out)")
2022-05-13 19:54:40,081 - zhuochuang_sj.py[line:758] - WARNING: (2003, "Can't connect to MySQL server on '27.150.182.135' (timed out)")
2022-05-13 20:07:36,701 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Read timed out. (read timeout=5)
2022-05-13 20:11:34,062 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Read timed out. (read timeout=5)
2022-05-13 20:11:34,171 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Read timed out. (read timeout=5)
2022-05-13 20:13:35,748 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Read timed out. (read timeout=5)
2022-05-13 21:33:40,296 - zhuochuang_sj.py[line:758] - WARNING: (2003, "Can't connect to MySQL server on '27.150.182.135' (timed out)")
2022-05-18 11:57:49,462 - zhuochuang_sj.py[line:758] - WARNING: (2003, "Can't connect to MySQL server on '27.150.182.135' (timed out)")
2022-05-18 12:00:06,721 - zhuochuang_sj.py[line:758] - WARNING: 27.150.182.135:27017: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
2022-05-18 12:02:00,453 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Read timed out. (read timeout=5)
2022-05-18 12:06:30,374 - zhuochuang_sj.py[line:758] - WARNING: (2003, "Can't connect to MySQL server on '27.150.182.135' (timed out)")
2022-05-18 12:29:39,639 - zhuochuang_sj.py[line:758] - WARNING: (2003, "Can't connect to MySQL server on '27.150.182.135' (timed out)")
2022-05-18 12:58:32,323 - zhuochuang_sj.py[line:758] - WARNING: (2013, 'Lost connection to MySQL server during query')
2022-05-18 12:58:32,844 - zhuochuang_sj.py[line:758] - WARNING: (2013, 'Lost connection to MySQL server during query')
2022-05-18 12:58:33,464 - zhuochuang_sj.py[line:758] - WARNING: (2013, 'Lost connection to MySQL server during query')
2022-05-18 12:58:34,902 - zhuochuang_sj.py[line:758] - WARNING: (2013, 'Lost connection to MySQL server during query')
2022-05-18 12:58:36,570 - zhuochuang_sj.py[line:758] - WARNING: (2013, 'Lost connection to MySQL server during query')
2022-05-18 12:58:36,755 - zhuochuang_sj.py[line:758] - WARNING: (2013, 'Lost connection to MySQL server during query')
2022-05-18 12:58:37,465 - zhuochuang_sj.py[line:758] - WARNING: (2013, 'Lost connection to MySQL server during query')
2022-05-18 12:58:39,137 - zhuochuang_sj.py[line:758] - WARNING: (2013, 'Lost connection to MySQL server during query')
2022-05-18 12:58:39,344 - zhuochuang_sj.py[line:758] - WARNING: (2013, 'Lost connection to MySQL server during query')
2022-05-18 12:58:39,949 - zhuochuang_sj.py[line:758] - WARNING: (2013, 'Lost connection to MySQL server during query')
2022-05-18 12:58:41,652 - zhuochuang_sj.py[line:758] - WARNING: (2013, 'Lost connection to MySQL server during query')
2022-05-18 12:58:41,930 - zhuochuang_sj.py[line:758] - WARNING: (2013, 'Lost connection to MySQL server during query')
2022-05-18 12:58:42,505 - zhuochuang_sj.py[line:758] - WARNING: (2013, 'Lost connection to MySQL server during query')
2022-05-18 13:45:32,609 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Read timed out. (read timeout=5)
2022-05-18 13:45:32,890 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Read timed out. (read timeout=5)
2022-05-18 13:45:37,816 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Read timed out. (read timeout=5)
2022-05-18 13:45:38,035 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Read timed out. (read timeout=5)
2022-05-18 13:54:18,060 - zhuochuang_sj.py[line:758] - WARNING: (2003, "Can't connect to MySQL server on '27.150.182.135' (timed out)")
2022-05-18 14:25:37,078 - zhuochuang_sj.py[line:758] - WARNING: (2003, "Can't connect to MySQL server on '27.150.182.135' (timed out)")
2022-05-20 14:23:57,699 - zhuochuang_sj.py[line:758] - WARNING: (2003, "Can't connect to MySQL server on '27.150.182.135' (timed out)")
2022-05-20 14:25:48,194 - zhuochuang_sj.py[line:758] - WARNING: (2003, "Can't connect to MySQL server on '27.150.182.135' (timed out)")
2022-05-20 14:27:06,480 - zhuochuang_sj.py[line:758] - WARNING: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2022-05-20 14:38:25,216 - zhuochuang_sj.py[line:758] - WARNING: (2013, 'Lost connection to MySQL server during query')
2022-05-20 14:39:19,794 - zhuochuang_sj.py[line:758] - WARNING: (2003, "Can't connect to MySQL server on '27.150.182.135' (timed out)")
2022-05-20 14:47:52,011 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Read timed out. (read timeout=5)
2022-05-20 15:04:41,337 - zhuochuang_sj.py[line:758] - WARNING: (2013, 'Lost connection to MySQL server during query')
2022-05-20 15:09:24,582 - zhuochuang_sj.py[line:758] - WARNING: 27.150.182.135:27017: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
2022-05-20 15:33:28,808 - zhuochuang_sj.py[line:758] - WARNING: 27.150.182.135:27017: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
2022-05-20 16:03:38,583 - zhuochuang_sj.py[line:758] - WARNING: (2013, 'Lost connection to MySQL server during query')
2022-05-20 16:04:31,082 - zhuochuang_sj.py[line:758] - WARNING: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2022-05-20 16:10:11,461 - zhuochuang_sj.py[line:758] - WARNING: (2003, "Can't connect to MySQL server on '27.150.182.135' (timed out)")
2022-05-20 16:15:06,615 - zhuochuang_sj.py[line:758] - WARNING: (2013, 'Lost connection to MySQL server during query')
2022-05-20 16:15:08,873 - zhuochuang_sj.py[line:758] - WARNING: (2013, 'Lost connection to MySQL server during query')
2022-05-20 16:15:09,374 - zhuochuang_sj.py[line:758] - WARNING: (2013, 'Lost connection to MySQL server during query')
2022-05-20 16:15:10,306 - zhuochuang_sj.py[line:758] - WARNING: (2013, 'Lost connection to MySQL server during query')
2022-05-20 16:15:11,586 - zhuochuang_sj.py[line:758] - WARNING: (2013, 'Lost connection to MySQL server during query')
2022-05-20 16:15:12,054 - zhuochuang_sj.py[line:758] - WARNING: (2013, 'Lost connection to MySQL server during query')
2022-05-20 16:15:13,927 - zhuochuang_sj.py[line:758] - WARNING: (2013, 'Lost connection to MySQL server during query')
2022-05-20 16:15:14,178 - zhuochuang_sj.py[line:758] - WARNING: (2013, 'Lost connection to MySQL server during query')
2022-05-20 16:27:53,153 - zhuochuang_sj.py[line:758] - WARNING: (2013, 'Lost connection to MySQL server during query')
2022-05-20 16:57:15,181 - zhuochuang_sj.py[line:758] - WARNING: (2013, 'Lost connection to MySQL server during query')
2022-05-20 17:07:07,074 - zhuochuang_sj.py[line:758] - WARNING: (2003, "Can't connect to MySQL server on '27.150.182.135' (timed out)")
2022-05-20 17:24:08,834 - zhuochuang_sj.py[line:758] - WARNING: (2003, "Can't connect to MySQL server on '27.150.182.135' (timed out)")
2022-05-20 17:24:19,899 - zhuochuang_sj.py[line:758] - WARNING: 27.150.182.135:27017: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
2022-05-20 17:28:21,619 - zhuochuang_sj.py[line:758] - WARNING: 27.150.182.135:27017: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
2022-05-20 17:41:00,435 - zhuochuang_sj.py[line:758] - WARNING: 27.150.182.135:27017: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
2022-05-20 17:52:49,105 - zhuochuang_sj.py[line:758] - WARNING: (2013, 'Lost connection to MySQL server during query')
2022-05-20 18:03:26,671 - zhuochuang_sj.py[line:758] - WARNING: (2013, 'Lost connection to MySQL server during query')
2022-05-25 21:02:04,347 - zhuochuang_sj.py[line:758] - WARNING: 27.150.182.135:27017: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
2022-05-25 21:25:35,931 - zhuochuang_sj.py[line:758] - WARNING: 27.150.182.135:27017: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
2022-05-25 21:48:39,322 - zhuochuang_sj.py[line:758] - WARNING: (2003, "Can't connect to MySQL server on '27.150.182.135' (timed out)")
2022-05-25 21:48:59,088 - zhuochuang_sj.py[line:758] - WARNING: 27.150.182.135:27017: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
2022-05-25 22:00:38,957 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Read timed out. (read timeout=5)
2022-05-25 22:12:07,717 - zhuochuang_sj.py[line:758] - WARNING: 27.150.182.135:27017: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
2022-05-25 23:37:41,864 - zhuochuang_sj.py[line:758] - WARNING: (2003, "Can't connect to MySQL server on '27.150.182.135' (timed out)")
2022-05-26 14:13:31,618 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:13:31,619 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:13:31,634 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:13:36,671 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:13:36,673 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:13:36,706 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:13:41,714 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:13:41,730 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:13:41,786 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:13:46,776 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:13:46,791 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:13:46,826 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:13:51,811 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:13:51,827 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:13:51,890 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:13:56,878 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:13:56,893 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:13:56,955 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:14:01,942 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:14:01,957 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:14:02,012 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:14:07,005 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:14:07,020 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:14:07,070 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:14:12,064 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:14:12,079 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:14:12,135 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:14:17,132 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:14:17,147 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:14:17,203 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:14:22,189 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:14:22,205 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:14:22,259 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:14:27,247 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:14:27,262 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:14:27,318 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:14:32,317 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:14:32,333 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:14:32,380 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:14:37,371 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:14:37,387 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:14:37,449 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:14:42,433 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:14:42,448 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:14:42,510 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:14:47,497 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:14:47,513 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:14:47,577 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:14:52,571 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:14:52,585 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:14:52,648 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:14:57,623 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:14:57,653 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:14:57,714 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:15:02,680 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:15:02,696 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:15:02,774 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:15:07,745 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:15:07,759 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:15:07,838 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:15:12,802 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:15:12,818 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:15:12,880 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:15:17,836 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:15:17,892 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:15:17,944 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:15:22,907 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:15:22,939 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:15:22,994 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:15:27,973 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:15:28,005 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:15:28,060 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:15:33,040 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:15:33,057 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:15:33,114 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:15:38,098 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:15:38,129 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:15:38,160 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:15:43,158 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:15:43,173 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:15:43,232 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:15:48,218 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:15:48,234 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:15:48,296 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:15:53,274 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:15:53,277 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:15:53,368 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:15:58,336 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:15:58,398 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:15:58,462 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:16:03,402 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:16:03,460 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:16:03,525 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:16:08,464 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:16:08,526 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:16:08,588 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:16:13,528 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:16:13,590 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:16:13,653 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:16:18,592 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:16:18,655 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:16:18,713 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:16:23,659 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:16:23,719 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:16:23,755 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:16:28,703 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:16:28,766 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:16:28,823 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:16:33,776 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:16:33,839 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:16:33,896 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:16:38,849 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:16:38,911 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:16:38,969 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:16:43,911 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:16:43,974 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:16:44,004 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:16:48,976 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:16:49,038 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:16:49,071 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:16:54,045 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:16:54,076 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:16:54,137 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:16:59,110 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:16:59,125 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:16:59,202 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:17:04,145 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:17:04,203 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:17:04,269 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:17:09,217 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:17:09,278 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:17:09,342 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:17:14,292 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:17:14,353 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Your proxy appears to only use HTTP and not HTTPS, try changing your proxy URL to be HTTP. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#https-proxy-error-http-proxy', SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1131)'))))
2022-05-26 14:17:14,355 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:17:14,417 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:17:19,402 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:17:19,418 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:17:19,481 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:17:24,480 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:17:24,480 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:17:24,527 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:17:29,527 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:17:29,530 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:17:29,590 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:17:34,582 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:17:34,582 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:17:34,664 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:17:39,676 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:17:39,677 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:17:39,758 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:17:44,744 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:17:44,774 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:17:44,820 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:17:49,797 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:17:49,859 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:17:49,888 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:17:54,848 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:17:54,926 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:17:54,958 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:17:59,912 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:17:59,990 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:18:00,022 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:18:04,979 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:18:05,058 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:18:05,089 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 14:18:08,166 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None)))
2022-05-26 14:18:08,175 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None)))
2022-05-26 14:18:08,177 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None)))
2022-05-26 14:40:12,459 - zhuochuang_sj.py[line:758] - WARNING: (2003, "Can't connect to MySQL server on '27.150.182.135' (timed out)")
2022-05-26 14:40:32,249 - zhuochuang_sj.py[line:758] - WARNING: 27.150.182.135:27017: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
2022-05-26 15:00:37,036 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Read timed out. (read timeout=5)
2022-05-26 15:04:57,269 - zhuochuang_sj.py[line:758] - WARNING: (2003, "Can't connect to MySQL server on '27.150.182.135' (timed out)")
2022-05-26 15:05:08,786 - zhuochuang_sj.py[line:758] - WARNING: (2003, "Can't connect to MySQL server on '27.150.182.135' (timed out)")
2022-05-26 15:05:28,693 - zhuochuang_sj.py[line:758] - WARNING: 27.150.182.135:27017: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
2022-05-26 15:28:34,020 - zhuochuang_sj.py[line:758] - WARNING: 27.150.182.135:27017: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
2022-05-26 15:39:54,583 - zhuochuang_sj.py[line:758] - WARNING: (2003, "Can't connect to MySQL server on '27.150.182.135' (timed out)")
2022-05-26 15:42:52,222 - zhuochuang_sj.py[line:758] - WARNING: (2003, "Can't connect to MySQL server on '27.150.182.135' (timed out)")
2022-05-26 15:50:32,764 - zhuochuang_sj.py[line:758] - WARNING: (2003, "Can't connect to MySQL server on '27.150.182.135' (timed out)")
2022-05-26 16:09:22,428 - zhuochuang_sj.py[line:758] - WARNING: (2003, "Can't connect to MySQL server on '27.150.182.135' (timed out)")
2022-05-26 16:33:20,810 - zhuochuang_sj.py[line:758] - WARNING: (2013, 'Lost connection to MySQL server during query')
2022-05-26 16:43:06,656 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Read timed out.
2022-05-26 16:43:06,920 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Read timed out.
2022-05-26 16:52:01,250 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Read timed out. (read timeout=5)
2022-05-26 16:53:40,852 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Read timed out. (read timeout=5)
2022-05-26 16:53:45,986 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Read timed out. (read timeout=5)
2022-05-26 17:05:26,694 - zhuochuang_sj.py[line:758] - WARNING: (2013, 'Lost connection to MySQL server during query')
2022-05-26 17:12:10,628 - zhuochuang_sj.py[line:758] - WARNING: (2013, 'Lost connection to MySQL server during query')
2022-05-26 17:38:36,822 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:38:40,169 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:38:41,880 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:38:45,238 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:38:46,936 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:38:50,031 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:38:50,312 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:38:52,008 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:38:55,114 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:38:55,394 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:38:57,068 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:39:00,191 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:39:00,486 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:39:02,118 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:39:05,273 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:39:05,552 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:39:07,183 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:39:10,363 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:39:10,625 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:39:12,249 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:39:15,446 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:39:15,695 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:39:17,317 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:39:20,536 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:39:20,769 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:39:22,396 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:39:25,620 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:39:25,823 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:39:27,466 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:39:30,694 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:39:30,912 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:39:32,543 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:39:35,759 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:39:35,993 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:39:37,621 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:39:40,848 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:39:40,927 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Your proxy appears to only use HTTP and not HTTPS, try changing your proxy URL to be HTTP. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#https-proxy-error-http-proxy', SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1131)'))))
2022-05-26 17:39:41,062 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:39:42,684 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:39:46,013 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:39:46,137 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:39:47,750 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:39:51,079 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:39:51,202 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:39:52,819 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:39:56,168 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:39:56,262 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:39:57,876 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:40:01,240 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:40:01,349 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:40:02,953 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:40:06,308 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:40:06,433 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:40:08,033 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:40:11,399 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:40:11,521 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:40:13,109 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:40:16,462 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:40:16,604 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:40:18,188 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:40:21,547 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:40:21,672 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:40:23,243 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:40:26,618 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:40:26,759 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:40:28,329 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:40:31,688 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:40:31,844 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:40:33,383 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:40:36,781 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:40:36,906 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:40:38,447 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:40:41,855 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:40:41,980 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:40:43,513 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:40:46,923 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:40:47,033 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:40:48,584 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:40:52,003 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:40:52,096 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:40:53,643 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:40:57,078 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:40:57,173 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:40:58,719 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:41:02,164 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:41:02,243 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:41:03,797 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:41:07,252 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:41:07,315 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:41:08,887 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:41:12,310 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:41:12,404 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:41:13,972 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:41:17,399 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:41:17,492 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:41:19,056 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:41:22,477 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:41:22,555 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:41:24,135 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:41:27,547 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:41:27,624 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:41:29,194 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:41:32,623 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:41:32,699 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:41:34,265 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:41:37,706 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:41:37,752 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:41:39,338 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:41:42,755 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:41:42,817 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:41:44,425 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:41:47,848 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:41:47,879 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:41:49,507 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:41:52,940 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:41:53,002 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:41:54,588 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:41:58,022 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:41:58,101 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:41:59,677 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:42:03,106 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:42:03,183 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:42:04,753 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:42:08,187 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:42:08,257 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:42:09,817 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:42:13,273 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:42:13,351 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:42:14,902 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:42:18,356 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:42:18,435 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:42:19,968 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:42:23,451 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:42:23,514 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:42:25,055 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:42:28,519 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:42:28,598 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:42:30,118 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:42:33,593 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:42:33,670 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:42:35,222 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:42:38,657 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:42:38,751 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:42:40,304 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:42:43,713 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:42:43,838 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:42:45,391 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:42:48,784 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:42:48,923 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:42:50,458 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:42:53,842 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:42:53,983 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:42:55,551 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:42:58,925 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:42:59,064 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:43:00,612 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:43:03,973 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:43:04,126 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:43:05,705 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:43:09,042 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:43:09,212 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:43:10,796 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:43:14,094 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:43:14,254 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:43:15,872 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:43:19,151 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:43:19,291 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:43:19,347 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Your proxy appears to only use HTTP and not HTTPS, try changing your proxy URL to be HTTP. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#https-proxy-error-http-proxy', SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1131)'))))
2022-05-26 17:43:20,948 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:43:24,227 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:43:24,416 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:43:26,035 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:43:29,300 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:43:30,461 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:43:31,112 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:43:34,399 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:43:35,515 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:43:36,196 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:43:39,485 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:43:40,601 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:43:41,286 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:43:44,562 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:43:45,680 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:43:46,376 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
2022-05-26 17:43:47,095 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None)))
2022-05-26 17:43:47,096 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None)))
2022-05-26 17:43:47,100 - zhuochuang_sj.py[line:758] - WARNING: HTTPSConnectionPool(host='prices.sci99.com', port=443): Max retries exceeded with url: /api/zh-cn/dataitem/datavalue (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None)))
2022-05-26 17:58:51,354 - zhuochuang_sj.py[line:758] - WARNING: (2013, 'Lost connection to MySQL server during query')
2022-05-26 18:00:41,831 - zhuochuang_sj.py[line:758] - WARNING: (2013, 'Lost connection to MySQL server during query')
